### ISSUE TITLE
FoundationDB as Storage Backend for JanusGraph: still feasible and advisable ?

### ISSUE THREAD

**Issue by raphael10-collab** [JanusGraph/janusgraph-foundationdb#62]
I'm interested to know the state of the JanusGraph-FoundationDB Storage Adapter:

4 years ago it was announced : https://www.youtube.com/watch?v=rQM_ZPZy8Ck&list=PLU8TPe7k8z9ew5W6YpACnGvjBDYaJVORZ&index=1

and, according to the README : https://github.com/JanusGraph/janusgraph-foundationdb the storage adapter is compatible only for the JanusGraph version 0.5.2 with FoundationDB version 6.2.22, while the latest JanusGraph version is 0.6.3 and the latest FoundationDB version is 7.2 (https://apple.github.io/foundationdb/ )

Since I don' see FoundationDB listed in storage backends

![image](https://user-images.githubusercontent.com/70313067/222769184-576514fa-fa93-4915-8a1e-beb23679c577.png) and there is no official JanusGraph documentation about FoundationDB as Backend Storage,

I would like to know if it is still feasible, and, more importantly, advisable, use FoundationDB as storage backend for JanusGraph

**Comment by FlorianHockmann** [comment]
This adapter isn't actively maintained right now. That explains why it isn't up to date with current JanusGraph versions and that is also why it's located in its own repository and why it is not documented in the JanusGraph documentation.
See #57 for more information.

Having said that, if you are interested in using JanusGraph with FoundationDB and are willing to contribute, then that would of course be highly welcome!
The adapter was created by @twilmes as an experiment and various contributors have already put in some effort to improve the quality of the adapter. But as mentioned in #57, some tests are currently not executed which is why the adapter should probably not be used in production right now.
If someone puts in the effort to get these tests green for the adapter, then we would have increased confidence in it and then we could also include it in the JanusGraph main repository which would make it much easier to keep it up to date with new JanusGraph versions.

**Comment by raphael10-collab** [comment]
Thank you very much
